import json
import os

descriptions = {
    "Mastering_RESTful_Web_Services_with_Java": "Building scalable and robust web services is a core requirement for modern distributed applications. However, designing APIs that are secure, performant, and truly RESTful can be challenging when navigating the Java ecosystem.\n\nMastering RESTful Web Services with Java provides a comprehensive guide to building enterprise-grade APIs. It covers advanced concepts, best practices, and practical implementation details using popular Java frameworks.\n\n• Design RESTful APIs following industry best practices\n• Implement security protocols including OAuth2 and JWT\n• Optimize performance and caching strategies for Java web services\n• Handle versioning and backward compatibility effectively\n• Test and document APIs using modern tools and frameworks",
    
    "Web_Scraping_With_Python": "Data is the lifeblood of the modern economy, but much of it is locked away on websites without public APIs. Extracting this data efficiently and reliably requires specialized tools and techniques.\n\nWeb Scraping with Python offers a practical deep dive into data extraction techniques. It guides you from basic HTML parsing to handling complex, JavaScript-heavy single-page applications.\n\n• Build robust web scrapers using BeautifulSoup and Scrapy\n• Navigate dynamic content rendering with Selenium and Playwright\n• Overcome anti-scraping protections and rate limits gracefully\n• Store extracted data efficiently in databases and flat files\n• Automate data pipelines and scheduled scraping tasks",
    
    "Build_Your_First_Home_Server": "Relying entirely on cloud services for data storage and self-hosted applications can lead to privacy concerns and recurring costs. Building a home server gives you control over your digital life but requires understanding networking, storage, and server administration.\n\nBuild Your First Home Server is a hands-on guide for enthusiasts looking to set up their own personal cloud. It covers hardware selection, OS installation, and deploying essential self-hosted services.\n\n• Choose the right hardware for your home server needs\n• Install and configure Linux or a specialized NAS OS\n• Deploy Docker containers for popular self-hosted applications\n• Secure your network with reverse proxies and VPNs\n• Implement automated backup strategies for data safety",
    
    "OpenClaw_AI_in_Production": "Transitioning AI models from experimental notebooks to robust production systems introduces complex engineering challenges. Ensuring reliability, scalability, and monitoring for AI agents requires a specialized infrastructure approach.\n\nOpenClaw: AI in Production provides architectural blueprints for deploying intelligent systems. It focuses on the operationalization of AI models and the engineering practices needed to maintain them at scale.\n\n• Architect scalable pipelines for AI inference and processing\n• Implement observability and monitoring for model performance\n• Design reliable error handling for non-deterministic AI outputs\n• Manage costs and resource allocation for production deployments\n• Orchestrate multi-agent interactions and workflows securely",
    
    "The_Modern_Guide_to_AI_Powered_Web_Scraping_and_Automation": "Traditional web scraping often breaks when website structures change, requiring constant maintenance. Integrating AI into scraping and automation workflows enables resilient systems that adapt to dynamic web environments.\n\nThe Modern Guide to AI-Powered Web Scraping and Automation explores the intersection of language models and data extraction. It demonstrates how to leverage LLMs to build autonomous agents capable of navigating and extracting unstructured data.\n\n• Replace brittle CSS selectors with semantic AI-driven parsing\n• Build autonomous agents capable of navigating complex websites\n• Extract structured JSON data directly from raw HTML using LLMs\n• Automate form submissions and interactions intelligently\n• Scale AI scraping operations while managing API costs",
    
    "Designing_Data_Intensive_Applications_2nd_Edition": "Data is at the center of many modern applications, demanding robust approaches to scale, consistency, and reliability. However, with an overwhelming number of tools and databases available, engineers often struggle to navigate the trade-offs and build systems that can withstand production workloads.\n\nDesigning Data-Intensive Applications 2nd Edition explores the principles and practicalities of building reliable, scalable, and maintainable data systems. This updated edition dives deeper into modern architectures, distributed systems, and the underlying algorithms.\n\n• Navigate the trade-offs between different database models and storage engines\n• Master the complexities of distributed systems, consensus, and replication\n• Build resilient data pipelines that can handle massive scale and high throughput\n• Evaluate the pros and cons of batch and stream processing architectures\n• Implement strategies for ensuring data consistency in unpredictable environments",
    
    "AI_Engineering_Interview": "The rise of AI engineering has created a new class of technical interviews focusing on LLMs, vector databases, and prompt engineering. Candidates often struggle to transition from traditional software engineering interviews to these specialized AI domains.\n\nAI Engineering Interview is a definitive resource for preparing for modern AI roles. It provides comprehensive coverage of the concepts, architectures, and practical problems encountered in AI engineering assessments.\n\n• Master the fundamentals of LLM architectures and capabilities\n• Design scalable RAG pipelines and vector search systems\n• Optimize prompts and model parameters for specific use cases\n• Evaluate and test non-deterministic AI outputs effectively\n• Architect robust AI agents and autonomous workflows",
    
    "Acing_the_System_Design_Interview": "System design interviews are notoriously difficult, requiring candidates to architect complex distributed systems under time pressure. Many engineers struggle to structure their thoughts and address scalability bottlenecks effectively.\n\nAcing the System Design Interview provides a systematic framework for tackling large-scale architectural challenges. It breaks down complex systems into manageable components and offers blueprints for common interview questions.\n\n• Apply a structured methodology to any system design question\n• Master core building blocks like load balancers, caches, and message queues\n• Design highly available and partition-tolerant distributed systems\n• Estimate capacity, throughput, and storage requirements accurately\n• Navigate trade-offs between consistency, availability, and performance",
    
    "Mastering_React_js_Interviews_For_MiddleSenior_Developers": "Senior frontend interviews go beyond basic component creation, focusing on performance, state management, and architectural decisions in React. Developers must demonstrate deep understanding of the reconciliation process and advanced hooks.\n\nMastering React.js Interviews provides an in-depth exploration of advanced React concepts. It prepares candidates to tackle complex scenarios, performance optimization challenges, and architectural discussions.\n\n• Explain the intricacies of the React reconciliation algorithm and Virtual DOM\n• Optimize performance using memoization, lazy loading, and concurrent features\n• Architect scalable state management solutions for large applications\n• Design reusable and testable custom hooks for complex logic\n• Discuss architectural trade-offs in client-side vs. server-side rendering"
}

with open("site/data.json", "r", encoding="utf-8") as f:
    data = json.load(f)

for book in data:
    if not book.get("download_url"):
        # Match title
        title = book["title"]
        if title in descriptions:
            book["description"] = descriptions[title]

with open("site/data.json", "w", encoding="utf-8") as f:
    json.dump(data, f, indent=2, ensure_ascii=False)
