#!/usr/bin/env python3
"""
Generate the .codex adapter from the shared .agents source of truth.

Usage:
    python scripts/sync_codex.py --base-dir .
    python scripts/sync_codex.py --base-dir . --check
"""

from __future__ import annotations

import argparse
import json
import sys
from dataclasses import dataclass
from pathlib import Path


GENERATED_NOTICE = "<!-- Generated by scripts/sync_codex.py. Do not edit by hand. -->"


@dataclass(frozen=True)
class WorkflowInfo:
    """Codex adapter metadata for one shared workflow."""

    name: str
    workflow_path: Path
    skill_path: Path | None
    prompt_path: Path | None
    settings_path: Path | None

    @property
    def adapter_path(self) -> Path:
        return Path(".codex") / "workflows" / f"{self.name}.md"


def as_posix(path: Path) -> str:
    """Return repo-relative paths in a stable slash format."""
    return path.as_posix()


def discover_workflows(base_dir: Path) -> list[WorkflowInfo]:
    """Discover shared workflows and matching skills by name."""
    workflows_dir = base_dir / ".agents" / "workflows"
    skills_dir = base_dir / ".agents" / "skills"

    if not workflows_dir.exists():
        raise FileNotFoundError(f"Missing workflows directory: {workflows_dir}")

    workflows: list[WorkflowInfo] = []
    for workflow_path in sorted(workflows_dir.glob("*.md")):
        name = workflow_path.stem
        skill_dir = skills_dir / name
        skill_path = skill_dir / "SKILL.md"
        prompt_path = skill_dir / "prompts" / "classify_book.md"
        settings_path = skill_dir / "config" / "settings.json"

        workflows.append(
            WorkflowInfo(
                name=name,
                workflow_path=workflow_path.relative_to(base_dir),
                skill_path=skill_path.relative_to(base_dir) if skill_path.exists() else None,
                prompt_path=prompt_path.relative_to(base_dir) if prompt_path.exists() else None,
                settings_path=settings_path.relative_to(base_dir)
                if settings_path.exists()
                else None,
            )
        )

    return workflows


def workflow_triggers(workflow: WorkflowInfo) -> list[str]:
    """Return useful trigger phrases for a workflow."""
    triggers = [f"/{workflow.name}", workflow.name]
    if workflow.name == "auto-organize":
        triggers.extend(
            [
                "phan loai sach",
                "sap xep sach",
                "classify books",
                "organize Inbox",
            ]
        )
    return triggers


def build_manifest(workflows: list[WorkflowInfo]) -> dict[str, object]:
    """Build the machine-readable Codex manifest."""
    workflow_entries: dict[str, object] = {}
    for workflow in workflows:
        entry: dict[str, object] = {
            "triggers": workflow_triggers(workflow),
            "codex_adapter": as_posix(workflow.adapter_path),
            "canonical_workflow": as_posix(workflow.workflow_path),
        }
        if workflow.skill_path:
            entry["canonical_skill"] = as_posix(workflow.skill_path)
        if workflow.prompt_path:
            entry["classification_prompt"] = as_posix(workflow.prompt_path)
        if workflow.settings_path:
            entry["settings"] = as_posix(workflow.settings_path)
        workflow_entries[workflow.name] = entry

    return {
        "schema_version": 1,
        "name": "my-bookshelves-codex-adapter",
        "purpose": (
            "Route Codex to the shared Antigravity/Codex agent instructions "
            "without duplicating source-of-truth behavior."
        ),
        "generated_by": "scripts/sync_codex.py",
        "read_order": [
            ".codex/manifest.json",
            ".codex/rules.md",
            "AGENTS.md",
            ".agents/rules/my-bookshelves.md",
        ],
        "source_of_truth": {
            "project_rules": ".agents/rules/my-bookshelves.md",
            "shared_workflows": ".agents/workflows",
            "shared_skills": ".agents/skills",
            "codex_entrypoint": "AGENTS.md",
        },
        "workflows": workflow_entries,
        "tool_mapping": {
            "view_file": (
                "Read the complete file with available Codex tooling or "
                "Get-Content -Raw."
            ),
            "multi_replace_file_content": (
                "Use apply_patch for batch edits, then validate the target file."
            ),
            "turbo_comment": "Optimization note only.",
            "bash_commands": (
                "Translate to PowerShell equivalents on Windows when needed."
            ),
        },
        "guardrails": [
            "Ask once before batch rename, move, upload, or commit/push.",
            "Run dry-run before destructive or upload operations.",
            "Never commit PDF, EPUB, DOCX, JPG, PNG, venv, node_modules, or IDE config.",
            "Preserve existing download_url and description fields in site/data.json.",
            "Use display names with spaces for category and topic in site/data.json.",
            "Validate JSON after editing JSON files.",
            "Log qualifying failures to ERRORS.md.",
        ],
        "commands": {
            "sync_codex": "python scripts/cli.py codex-sync --base-dir .",
            "list": "python scripts/cli.py list --base-dir .",
            "rename_dry_run": "python scripts/cli.py rename --base-dir .",
            "rename_execute": "python scripts/cli.py rename --base-dir . --execute",
            "generate": "python scripts/cli.py generate --base-dir .",
            "structure": "python scripts/cli.py structure --base-dir .",
            "upload_dry_run": "python scripts/cli.py upload --dry-run",
            "upload": "python scripts/cli.py upload",
        },
        "data_files": {
            "library_structure": "library_structure.log",
            "book_metadata": "site/data.json",
            "covers": "site/assets/covers",
            "inbox": "Inbox",
            "books": "Books",
        },
    }


def build_readme(workflows: list[WorkflowInfo]) -> str:
    """Build .codex/README.md."""
    workflow_rows = "\n".join(
        f"| `{workflow.name}` | `{as_posix(workflow.adapter_path)}` |"
        for workflow in workflows
    )
    return f"""{GENERATED_NOTICE}
# Codex Readme

This directory is the generated Codex adapter for My-Bookshelves.

Codex should read this directory first, then use `.agents/` as the shared
source of truth with Antigravity.

## Fast Read Order

1. `.codex/manifest.json`
2. `.codex/rules.md`
3. `AGENTS.md`
4. `.agents/rules/my-bookshelves.md`
5. The requested workflow under `.codex/workflows/`
6. The canonical skill/workflow files referenced by the workflow

## Generated Files

Run this after changing `.agents/`:

```powershell
python scripts/cli.py codex-sync --base-dir .
```

## Workflows

| Workflow | Codex adapter |
| --- | --- |
{workflow_rows}

## Source Of Truth

| Purpose | Path |
| --- | --- |
| Codex routing | `.codex/manifest.json` |
| Codex rules summary | `.codex/rules.md` |
| Main Codex entrypoint | `AGENTS.md` |
| Shared project rules | `.agents/rules/my-bookshelves.md` |
| Shared workflows | `.agents/workflows/` |
| Shared skills | `.agents/skills/` |

Do not fork behavior into `.codex/` unless it is Codex-specific. If the
behavior should apply to both Codex and Antigravity, update `.agents/` and run
`codex-sync`.
"""


def build_rules() -> str:
    """Build .codex/rules.md."""
    return f"""{GENERATED_NOTICE}
# Codex Rules Summary

Canonical rules: `.agents/rules/my-bookshelves.md`.

This file is the compact Codex reminder.

## Repository Model

- Static personal library hosted from `site/`.
- Books live under `Books/` locally but are uploaded to GitHub Releases.
- Git should contain metadata, covers, scripts, and site files, not book binaries.
- `.agents/` is shared by Antigravity and Codex.
- `.codex/` is generated by `scripts/sync_codex.py`.

## Coding Rules

- Keep frontend zero-dependency: vanilla HTML, CSS, and JavaScript only.
- Do not introduce React, Vue, Tailwind, Bootstrap, jQuery, FontAwesome, CDNs, or external assets.
- Keep Python scripts typed, pathlib-based, argparse-friendly, and explicit about errors.
- Do not leave placeholder or TODO implementations.

## Data Rules

- Folder names use `Snake_Case`.
- `site/data.json` display fields use spaces, not underscores.
- Example folder: `Programming_Languages/Java`.
- Correct topic display: `Programming Languages/Java`.
- Incorrect topic display: `Programming_Languages/Java`.
- Never remove existing `download_url` or `description` values while regenerating or editing metadata.

## Workflow Rules

- Read the relevant workflow and skill before acting.
- Prefer dry-run commands before any destructive action.
- Ask the user one time before batch rename, move, upload, or commit/push.
- Run `python scripts/cli.py structure --base-dir .` after adding or moving books.
- Verify dependencies before generating data: PyMuPDF, Pillow, python-docx.
- Run `python scripts/cli.py generate --base-dir .` only once per batch unless a failure root cause has been fixed.

## Failure Logging

If a test, build, lint, runtime, integration, or agent-process failure occurs,
append an entry to `ERRORS.md` using the workspace error format.
"""


def build_workflow_adapter(workflow: WorkflowInfo) -> str:
    """Build one .codex workflow adapter."""
    references = [workflow.workflow_path]
    if workflow.skill_path:
        references.append(workflow.skill_path)
    if workflow.prompt_path:
        references.append(workflow.prompt_path)
    if workflow.settings_path:
        references.append(workflow.settings_path)
    references.append(Path(".agents/rules/my-bookshelves.md"))
    reference_lines = "\n".join(f"- `{as_posix(path)}`" for path in references)

    return f"""{GENERATED_NOTICE}
# Codex Workflow: {workflow.name}

Use this when the user asks for `{workflow.name}` or one of its trigger phrases
listed in `.codex/manifest.json`.

This file is an adapter. The canonical workflow remains in `.agents/`.

## Canonical References

{reference_lines}

## Required Preload

1. `.codex/manifest.json`
2. `.codex/rules.md`
3. `.agents/rules/my-bookshelves.md`
4. The canonical workflow listed above
5. The canonical skill and prompt listed above, when present

## Codex Execution Rules

- Translate Antigravity-only tool names using `.codex/manifest.json`.
- Use PowerShell-safe commands on Windows.
- Run dry-runs before destructive or upload steps.
- Ask once before batch rename, move, upload, commit, or push.
- If the canonical workflow and this adapter conflict, follow the canonical workflow unless the difference is Codex-specific tooling.

## Stop Conditions

- A dry-run count is larger than the expected new-item count.
- Metadata validation fails.
- `site/data.json` would lose existing `download_url` or `description` values.
- A dependency check fails and cannot be fixed with the documented install command.

If a stop condition happens, stop and explain the root cause. Log qualifying
failures to `ERRORS.md`.
"""


def write_if_changed(path: Path, content: str, check: bool) -> bool:
    """Write content unless --check is active. Return True when changed."""
    old_content = path.read_text(encoding="utf-8") if path.exists() else None
    if old_content == content:
        return False
    if check:
        return True
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")
    return True


def sync_codex(base_dir: Path, check: bool) -> list[Path]:
    """Generate all Codex adapter files."""
    workflows = discover_workflows(base_dir)
    codex_dir = base_dir / ".codex"
    changed: list[Path] = []

    files = {
        codex_dir / "manifest.json": json.dumps(
            build_manifest(workflows), ensure_ascii=False, indent=2
        )
        + "\n",
        codex_dir / "README.md": build_readme(workflows),
        codex_dir / "rules.md": build_rules(),
    }

    for workflow in workflows:
        files[base_dir / workflow.adapter_path] = build_workflow_adapter(workflow)

    for path, content in files.items():
        if write_if_changed(path, content, check):
            changed.append(path.relative_to(base_dir))

    return changed


def parse_args() -> argparse.Namespace:
    """Parse command line arguments."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--base-dir",
        default=".",
        help="Repository root. Defaults to current directory.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit non-zero if generated .codex files are stale.",
    )
    return parser.parse_args()


def main() -> int:
    """CLI entry point."""
    args = parse_args()
    base_dir = Path(args.base_dir).resolve()

    try:
        changed = sync_codex(base_dir, args.check)
    except Exception as exc:
        print(f"codex-sync failed: {exc}", file=sys.stderr)
        return 1

    if args.check and changed:
        print(".codex is stale. Run: python scripts/cli.py codex-sync --base-dir .")
        for path in changed:
            print(f"  - {path}")
        return 1

    if changed:
        print("Updated .codex adapter files:")
        for path in changed:
            print(f"  - {path}")
    else:
        print(".codex is already up to date.")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
